"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-06 04:39:09.915880

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base  # noqa: F401  提供 UtcDateTime 自定义类型


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('client_version', sa.String(length=32), nullable=True),
    sa.Column('os_info', sa.String(length=128), nullable=True),
    sa.Column('last_seen_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_state', sa.String(length=24), nullable=True),
    sa.Column('last_state_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('paired_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','retired')", name=op.f('ck_devices_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('in_progress','completed')", name=op.f('ck_idempotency_keys_state_valid')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin','parent')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('used_minutes', sa.Integer(), nullable=False),
    sa.Column('bonus_minutes', sa.Integer(), nullable=False),
    sa.Column('parent_minutes', sa.Integer(), nullable=False),
    sa.Column('break_count', sa.Integer(), nullable=False),
    sa.Column('base_quota_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_daily_usage_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_usage')),
    sa.UniqueConstraint('device_id', 'usage_date', name='uq_daily_usage_device_date')
    )
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.create_index('ix_daily_usage_device_date', ['device_id', 'usage_date'], unique=False)

    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('secret_lookup', sa.String(length=64), nullable=False),
    sa.Column('issued_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_credentials_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_credentials'))
    )
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_credentials_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_credentials_secret_lookup'), ['secret_lookup'], unique=False)
        batch_op.create_index('uq_device_credentials_active', ['device_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'))

    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_event_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('occurred_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('info','warning','error')", name=op.f('ck_event_logs_severity_valid')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_event_logs_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_logs'))
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_logs_client_event_id'), ['client_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_event_logs_device_occurred', ['device_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_event_logs_type_occurred', ['event_type', 'occurred_at'], unique=False)

    op.create_table('extension_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('requested_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_minutes', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('credited_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('client_created_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected','expired','credited')", name=op.f('ck_extension_requests_status_valid')),
    sa.CheckConstraint('approved_minutes IS NULL OR approved_minutes BETWEEN 0 AND 240', name=op.f('ck_extension_requests_approved_minutes_range')),
    sa.CheckConstraint('requested_minutes BETWEEN 1 AND 240', name=op.f('ck_extension_requests_requested_minutes_range')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_extension_requests_decided_by_users')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_extension_requests_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extension_requests'))
    )
    with op.batch_alter_table('extension_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_requests_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_extension_requests_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_requests_status'), ['status'], unique=False)
        batch_op.create_index('ix_extension_requests_target_date', ['target_date'], unique=False)

    op.create_table('pairing_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('code_prefix', sa.String(length=4), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pairing_codes_created_by_users')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_pairing_codes_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing_codes'))
    )
    with op.batch_alter_table('pairing_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairing_codes_code_hash'), ['code_hash'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('remote_commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('acked_at', app.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','delivered','acked','expired')", name=op.f('ck_remote_commands_status_valid')),
    sa.CheckConstraint("type IN ('UNLOCK_TEMP','PAUSE_ENFORCEMENT','RESUME_ENFORCEMENT','SYNC_NOW')", name=op.f('ck_remote_commands_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_remote_commands_created_by_users')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_remote_commands_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remote_commands'))
    )
    with op.batch_alter_table('remote_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_commands_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_commands_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_remote_commands_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_commands_status'), ['status'], unique=False)

    op.create_table('rule_profiles',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('weekday_quota_minutes', sa.Integer(), nullable=False),
    sa.Column('weekend_quota_minutes', sa.Integer(), nullable=False),
    sa.Column('allowed_start', sa.String(length=5), nullable=False),
    sa.Column('allowed_end', sa.String(length=5), nullable=False),
    sa.Column('continuous_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('idle_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_points_json', sa.Text(), nullable=False),
    sa.Column('parent_mode_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enforcement_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('break_minutes BETWEEN 1 AND 60', name=op.f('ck_rule_profiles_break_minutes_range')),
    sa.CheckConstraint('continuous_limit_minutes BETWEEN 10 AND 240', name=op.f('ck_rule_profiles_continuous_limit_range')),
    sa.CheckConstraint('idle_minutes BETWEEN 1 AND 60', name=op.f('ck_rule_profiles_idle_minutes_range')),
    sa.CheckConstraint('parent_mode_timeout_minutes BETWEEN 5 AND 120', name=op.f('ck_rule_profiles_parent_timeout_range')),
    sa.CheckConstraint('sync_interval_seconds BETWEEN 15 AND 300', name=op.f('ck_rule_profiles_sync_interval_range')),
    sa.CheckConstraint('weekday_quota_minutes BETWEEN 0 AND 1440', name=op.f('ck_rule_profiles_weekday_quota_range')),
    sa.CheckConstraint('weekend_quota_minutes BETWEEN 0 AND 1440', name=op.f('ck_rule_profiles_weekend_quota_range')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_rule_profiles_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_rule_profiles_updated_by_users')),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_rule_profiles'))
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_layout_json', sa.String(length=512), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("theme IN ('light','dark','system')", name=op.f('ck_user_preferences_theme_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('rule_profiles')
    with op.batch_alter_table('remote_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_commands_status'))
        batch_op.drop_index('ix_remote_commands_device_status')
        batch_op.drop_index(batch_op.f('ix_remote_commands_device_id'))
        batch_op.drop_index(batch_op.f('ix_remote_commands_batch_id'))

    op.drop_table('remote_commands')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('pairing_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairing_codes_code_hash'))

    op.drop_table('pairing_codes')
    with op.batch_alter_table('extension_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_extension_requests_target_date')
        batch_op.drop_index(batch_op.f('ix_extension_requests_status'))
        batch_op.drop_index('ix_extension_requests_device_status')
        batch_op.drop_index(batch_op.f('ix_extension_requests_device_id'))

    op.drop_table('extension_requests')
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_event_logs_type_occurred')
        batch_op.drop_index(batch_op.f('ix_event_logs_event_type'))
        batch_op.drop_index('ix_event_logs_device_occurred')
        batch_op.drop_index(batch_op.f('ix_event_logs_device_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_client_event_id'))

    op.drop_table('event_logs')
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.drop_index('uq_device_credentials_active', sqlite_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_device_credentials_secret_lookup'))
        batch_op.drop_index(batch_op.f('ix_device_credentials_device_id'))

    op.drop_table('device_credentials')
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_usage_device_date')

    op.drop_table('daily_usage')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_created_at'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_last_seen_at'))

    op.drop_table('devices')
    # ### end Alembic commands ###
