"""rule_templates + rule_profiles.template_id

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-10 10:00:00.000000

"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base  # noqa: F401  提供 UtcDateTime 自定义类型


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('weekday_quota_minutes', sa.Integer(), nullable=False),
    sa.Column('weekend_quota_minutes', sa.Integer(), nullable=False),
    sa.Column('allowed_start', sa.String(length=5), nullable=False),
    sa.Column('allowed_end', sa.String(length=5), nullable=False),
    sa.Column('continuous_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('idle_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_points_json', sa.Text(), nullable=False),
    sa.Column('parent_mode_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enforcement_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('break_minutes BETWEEN 1 AND 60', name=op.f('ck_rule_templates_break_minutes_range')),
    sa.CheckConstraint('continuous_limit_minutes BETWEEN 10 AND 240', name=op.f('ck_rule_templates_continuous_limit_range')),
    sa.CheckConstraint('idle_minutes BETWEEN 1 AND 60', name=op.f('ck_rule_templates_idle_minutes_range')),
    sa.CheckConstraint('parent_mode_timeout_minutes BETWEEN 5 AND 120', name=op.f('ck_rule_templates_parent_timeout_range')),
    sa.CheckConstraint('sync_interval_seconds BETWEEN 15 AND 300', name=op.f('ck_rule_templates_sync_interval_range')),
    sa.CheckConstraint('weekday_quota_minutes BETWEEN 0 AND 1440', name=op.f('ck_rule_templates_weekday_quota_range')),
    sa.CheckConstraint('weekend_quota_minutes BETWEEN 0 AND 1440', name=op.f('ck_rule_templates_weekend_quota_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rule_templates_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_rule_templates_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_templates'))
    )
    with op.batch_alter_table('rule_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rule_profiles_template_id_rule_templates'), 'rule_templates', ['template_id'], ['id'], ondelete='SET NULL')

    # 内置默认模板 seed（值 = app/core/constants.py 默认值，与代码同步维护）
    # 默认：weekday 40 / weekend 40 / 08:00-21:00 / 30 / 10 / 5 / [10,5,1] / 15 / 45 / 管控开
    # （2026-09-05 用户裁决统一默认值；client-preview 模板库每次重建，改值安全）
    seed_timestamp = datetime.now(timezone.utc)
    op.bulk_insert(
        sa.table(
            'rule_templates',
            sa.column('name', sa.String(length=64)),
            sa.column('description', sa.String(length=255)),
            sa.column('is_builtin', sa.Boolean()),
            sa.column('weekday_quota_minutes', sa.Integer()),
            sa.column('weekend_quota_minutes', sa.Integer()),
            sa.column('allowed_start', sa.String(length=5)),
            sa.column('allowed_end', sa.String(length=5)),
            sa.column('continuous_limit_minutes', sa.Integer()),
            sa.column('break_minutes', sa.Integer()),
            sa.column('idle_minutes', sa.Integer()),
            sa.column('reminder_points_json', sa.Text()),
            sa.column('parent_mode_timeout_minutes', sa.Integer()),
            sa.column('sync_interval_seconds', sa.Integer()),
            sa.column('enforcement_enabled', sa.Boolean()),
            sa.column('version', sa.Integer()),
            sa.column('created_by', sa.Integer()),
            sa.column('created_at', app.db.base.UtcDateTime(timezone=True)),
            sa.column('updated_at', app.db.base.UtcDateTime(timezone=True)),
            sa.column('updated_by', sa.Integer()),
        ),
        [
            {
                'name': '默认模板',
                'description': '系统内置默认规则',
                'is_builtin': True,
                'weekday_quota_minutes': 40,
                'weekend_quota_minutes': 40,
                'allowed_start': '08:00',
                'allowed_end': '21:00',
                'continuous_limit_minutes': 30,
                'break_minutes': 10,
                'idle_minutes': 5,
                'reminder_points_json': '[10, 5, 1]',
                'parent_mode_timeout_minutes': 15,
                'sync_interval_seconds': 45,
                'enforcement_enabled': True,
                'version': 1,
                'created_by': None,
                'created_at': seed_timestamp,
                'updated_at': seed_timestamp,
                'updated_by': None,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rule_profiles_template_id_rule_templates'), type_='foreignkey')
        batch_op.drop_column('template_id')

    op.drop_table('rule_templates')
    # ### end Alembic commands ###
